spring:
  application:
    name: demo-web

server:
  port: 8888
  ssl:
    key-store: classpath:demoweb.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: demoweb
    #key-password: